# Generated by Django 3.2.16 on 2024-05-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaofertada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professor.professor', verbose_name='Professor'),
        ),
    ]
