# Generated by Django 3.2.16 on 2024-01-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0003_auto_20230206_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carater',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
