# Generated by Django 3.2.16 on 2024-09-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0009_auto_20240922_2100'),
        ('matricula', '0013_remove_matricula_membro_colegiado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegiado_data_entrada', models.DateField()),
                ('colegiado_data_saida', models.DateField(blank=True, null=True)),
                ('status_membro', models.CharField(choices=[('Titular', 'Titular'), ('Suplente', 'Suplente')], max_length=100, verbose_name='Status:')),
                ('matricula_membro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.matricula')),
                ('professor_membro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='professor.professor')),
            ],
        ),
    ]
