# Generated by Django 2.1.5 on 2022-08-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('saida', models.DateField()),
                ('retorno', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('agencia', models.CharField(max_length=200)),
                ('dt_inicio', models.DateField()),
                ('iniciacao_cientifica', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_aluno', to='aluno.Aluno')),
            ],
        ),
        migrations.AddField(
            model_name='bolsa',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bolsa_matricula', to='matricula.Matricula'),
        ),
    ]
