# Generated by Django 3.2.15 on 2022-10-10 12:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('saida', models.DateField()),
                ('retorno', models.DateField()),
                ('dt_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique_for_date='dt_cadastro')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('disciplina_ofertada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_disciplina_ofertada', to='disciplina.disciplinaofertada')),
            ],
        ),
        migrations.CreateModel(
            name='Probatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField()),
                ('nota', models.FloatField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('slug', models.SlugField(max_length=250, unique_for_date='dt_cadastro')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dt_cadastro', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='probatorio_aluno', to='aluno.aluno')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='probatorio_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('inscricao_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='probatorio_inscricao', to='matricula.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=250, unique_for_date='dt_cadastro')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dt_cadastro', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('inscricao_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_inscricao', to='matricula.inscricao')),
                ('probatorio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_probatorio', to='matricula.probatorio')),
            ],
        ),
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('agencia', models.CharField(max_length=200)),
                ('dt_inicio', models.DateField()),
                ('iniciacao_cientifica', models.BooleanField()),
                ('dt_cadastro', models.DateTimeField(auto_now=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bolsa_matricula', to='matricula.matricula')),
            ],
        ),
    ]
