# Generated by Django 3.2.16 on 2024-05-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matricula', '0001_initial'),
        ('config', '0001_initial'),
        ('professor', '0001_initial'),
        ('disciplina', '0002_disciplinaofertada_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orientacao_professor', to='professor.professor'),
        ),
        migrations.AddField(
            model_name='orientacao',
            name='trabalho_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orientacao_trabalho_final', to='matricula.trabalhofinal'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='cadastrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_curso', to='matricula.curso', verbose_name='Curso:'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_grau', to='config.grau', verbose_name='Grau de Aplicação:'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='linha_pesquisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.linhapesquisa'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='probatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_probatorio', to='matricula.probatorio', verbose_name='Probatório:'),
        ),
        migrations.AddField(
            model_name='inscricaoprobatorio',
            name='cadastrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_probatorio_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricaoprobatorio',
            name='disciplina_ofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_probatorio_disciplina_ofertada', to='disciplina.disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='inscricaoprobatorio',
            name='probatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_probatorio_probatorio', to='matricula.probatorio'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='cadastrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='disciplina_ofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_disciplina_ofertada', to='disciplina.disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_matricula', to='matricula.matricula'),
        ),
        migrations.AddField(
            model_name='examelinguas',
            name='lingua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exame_linguas', to='config.linguas'),
        ),
        migrations.AddField(
            model_name='examelinguas',
            name='probatorio',
            field=models.ManyToManyField(related_name='probatorio_exame_linguas', to='matricula.Probatorio'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsa_matricula', to='matricula.matricula', verbose_name='Matrícula:'),
        ),
        migrations.AddField(
            model_name='afastamento',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamento_matricula', to='matricula.matricula', verbose_name='Matrícula:'),
        ),
    ]
