# Generated by Django 2.1.5 on 2022-08-25 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0002_disciplinaofertada'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_ofertada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_disciplina_ofertada', to='disciplina.DisciplinaOfertada')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_matricula', to='matricula.Matricula')),
            ],
        ),
    ]
