# Generated by Django 3.2.16 on 2023-01-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Titulado', 'Titulado'), ('Jubilado', 'Jubilado'), ('Abandono', 'Abandono')], default='Ativo', max_length=20),
        ),
    ]
