# Generated by Django 3.2.16 on 2022-10-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_auto_20221010_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='inscricao_disciplina',
        ),
        migrations.RemoveField(
            model_name='probatorio',
            name='inscricao_disciplina',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='matricula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_matricula', to='matricula.matricula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='probatorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_probatorio', to='matricula.probatorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='requisita_bolsa',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
