# Generated by Django 2.1.5 on 2022-08-25 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matricula', '0002_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='cadastrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_cadastrado_por', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='dt_cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
