# Generated by Django 3.2.16 on 2022-10-21 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_remove_inscricao_probatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='nota',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
