# Generated by Django 3.2.16 on 2022-10-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_auto_20221014_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probatorio',
            name='curso',
        ),
    ]
