# Generated by Django 3.2.16 on 2023-01-04 12:36

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplina', '0001_initial'),
        ('matricula', '0003_auto_20230104_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 1, 4, 9, 36, 13, 179971)),
        ),
        migrations.CreateModel(
            name='InscricaoProbatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(max_length=250, unique_for_date='dt_cadastro')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_probatorio_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('disciplina_ofertada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_probatorio_disciplina_ofertada', to='disciplina.disciplinaofertada')),
                ('probatorio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscricao_probatorio_probatorio', to='matricula.probatorio')),
            ],
        ),
    ]
