# Generated by Django 3.2.16 on 2024-05-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_probatorio_nota_selecao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsa',
            name='iniciacao_cientifica',
        ),
        migrations.AddField(
            model_name='bolsa',
            name='dt_final',
            field=models.DateField(default='2020-01-01', verbose_name='Data Final:'),
            preserve_default=False,
        ),
    ]
