# Generated by Django 3.2.16 on 2022-10-24 11:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_inscricao_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhoFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('data', models.DateField()),
                ('resumo', models.TextField()),
                ('resultado', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('diploma', models.BooleanField()),
                ('dt_diploma', models.DateField()),
                ('versao_final', models.BooleanField()),
                ('dt_versao', models.DateField()),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_trabalho_final', to='matricula.matricula')),
            ],
        ),
    ]
