# Generated by Django 3.2.16 on 2022-10-14 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_remove_probatorio_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probatorio',
            name='nota',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
