# Generated by Django 3.2.16 on 2022-10-24 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matricula', '0004_trabalhofinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhofinal',
            name='cadastrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trabalho_final_cadastrado_por', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabalhofinal',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='dt_cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabalhofinal',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
