# Generated by Django 3.2.16 on 2023-01-04 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0004_auto_20230104_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhofinal',
            name='probatorio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='probatorio_trabalho_final', to='matricula.probatorio'),
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 1, 4, 9, 40, 58, 251380)),
        ),
        migrations.AlterField(
            model_name='trabalhofinal',
            name='matricula',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_trabalho_final', to='matricula.matricula'),
        ),
    ]
