# Generated by Django 3.2.15 on 2022-10-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=200)),
                ('orientador', models.CharField(max_length=200)),
                ('coorientador', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_curso', to='matricula.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='probatorio',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='probatorio_curso', to='matricula.curso'),
            preserve_default=False,
        ),
    ]
