# Generated by Django 3.2.16 on 2022-10-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_alter_probatorio_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_curso', to='matricula.curso'),
        ),
    ]
