# Generated by Django 3.2.16 on 2024-05-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_rename_agencia_agenciafomento_agencia_fomento'),
        ('matricula', '0005_alter_bolsa_agencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsa',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bolsa_agencia', to='config.agenciafomento', verbose_name='Agência de Fomento:'),
        ),
    ]
