# Generated by Django 3.2.16 on 2022-10-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_alter_matricula_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='afastamento',
            name='matricula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='afastamento_matricula', to='matricula.matricula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(default='Matriculado', max_length=50),
        ),
    ]
