# Generated by Django 3.2.16 on 2024-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0007_alter_professor_membro_colegiado'),
        ('matricula', '0007_rename_agencia_bolsa_bolsa_agencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='membro_colegiado',
            field=models.ManyToManyField(blank=True, related_name='matricula_colegiado', to='professor.Colegiado'),
        ),
    ]
