# Generated by Django 3.2.16 on 2024-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0008_matricula_membro_colegiado'),
    ]

    operations = [
        migrations.AddField(
            model_name='probatorio',
            name='data_limite',
            field=models.DateField(default='2024-07-10'),
            preserve_default=False,
        ),
    ]
