# Generated by Django 3.2.16 on 2024-07-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0009_probatorio_data_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='probatorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_probatorio_probatorio', to='matricula.probatorio'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_matricula', to='matricula.matricula'),
        ),
        migrations.DeleteModel(
            name='InscricaoProbatorio',
        ),
    ]
