# Generated by Django 3.2.16 on 2023-02-02 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_alter_trabalho_tipo_vinculo'),
        ('matricula', '0009_alter_probatorio_data_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='probatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_probatorio', to='matricula.probatorio'),
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probatorio_aluno', to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 11, 34, 59, 454407)),
        ),
    ]
