# Generated by Django 3.2.16 on 2024-09-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0008_auto_20240922_1949'),
        ('matricula', '0011_auto_20240922_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='membro_colegiado',
        ),
        migrations.AddField(
            model_name='matricula',
            name='membro_colegiado',
            field=models.ManyToManyField(blank=True, related_name='matricula_colegiado', to='professor.Colegiado'),
        ),
    ]
