# Generated by Django 3.2.16 on 2024-09-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0012_auto_20240922_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='membro_colegiado',
        ),
    ]
