# Generated by Django 3.2.16 on 2023-02-02 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0002_auto_20230131_1130'),
        ('matricula', '0012_auto_20230202_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamento',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamento_matricula', to='matricula.matricula'),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsa_matricula', to='matricula.matricula'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='disciplina_ofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_disciplina_ofertada', to='disciplina.disciplinaofertada'),
        ),
        migrations.AlterField(
            model_name='inscricaoprobatorio',
            name='disciplina_ofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_probatorio_disciplina_ofertada', to='disciplina.disciplinaofertada'),
        ),
        migrations.AlterField(
            model_name='inscricaoprobatorio',
            name='probatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_probatorio_probatorio', to='matricula.probatorio'),
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 11, 57, 56, 356701)),
        ),
    ]
