# Generated by Django 3.2.16 on 2023-02-07 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0014_auto_20230206_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 2, 7, 8, 42, 14, 901282)),
        ),
    ]
