# Generated by Django 3.2.16 on 2023-02-16 10:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0009_alter_aluno_foto'),
        ('matricula', '0015_alter_probatorio_data_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersaoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_final', models.BooleanField()),
                ('dt_versao', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trabalhofinal',
            name='dt_versao',
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamento_matricula', to='matricula.matricula', verbose_name='Matrícula:'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='motivo',
            field=models.CharField(max_length=200, verbose_name='Motivo:'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='retorno',
            field=models.DateField(verbose_name='Retorno:'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='saida',
            field=models.DateField(verbose_name='Saída:'),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='agencia',
            field=models.CharField(max_length=200, verbose_name='Agência:'),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='dt_inicio',
            field=models.DateField(verbose_name='Data de início:'),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='iniciacao_cientifica',
            field=models.BooleanField(verbose_name='Iniciação científica:'),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsa_matricula', to='matricula.matricula', verbose_name='Matrícula:'),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Bolsa:'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='coorientador',
            field=models.CharField(max_length=200, verbose_name='Coorientador:'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso',
            field=models.CharField(choices=[('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=200, verbose_name='Curso:'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='orientador',
            field=models.CharField(max_length=200, verbose_name='Orientador:'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matricula_curso', to='matricula.curso', verbose_name='Curso:'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número:'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='probatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_probatorio', to='matricula.probatorio', verbose_name='Probatório:'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='requisita_bolsa',
            field=models.BooleanField(verbose_name='Requisita bolsa:'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Titulado', 'Titulado'), ('Jubilado', 'Jubilado'), ('Abandono', 'Abandono')], default='Ativo', max_length=20, verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probatorio_aluno', to='aluno.aluno', verbose_name='Aluno:'),
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 7, 29, 20, 337344), verbose_name='Data da inscrição:'),
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='nota',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Nota:'),
        ),
        migrations.AlterField(
            model_name='trabalhofinal',
            name='diploma',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabalhofinal',
            name='dt_diploma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabalhofinal',
            name='versao_final',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versao_final_trabalho_final', to='matricula.versaofinal'),
        ),
    ]
