# Generated by Django 3.2.16 on 2023-02-16 10:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0016_auto_20230216_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('dt_nota', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trabalhofinal',
            name='resultado',
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 7, 33, 24, 337972), verbose_name='Data da inscrição:'),
        ),
        migrations.AddField(
            model_name='trabalhofinal',
            name='nota',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_trabalho_final', to='matricula.nota'),
        ),
    ]
