# Generated by Django 3.2.16 on 2023-02-16 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20230207_0842'),
        ('matricula', '0017_auto_20230216_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhofinal',
            name='orientador',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orientador_trabalho_final', to='professor.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 7, 40, 12, 621528), verbose_name='Data da inscrição:'),
        ),
    ]
