# Generated by Django 3.2.16 on 2023-02-16 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20230207_0842'),
        ('matricula', '0019_alter_probatorio_data_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 9, 28, 46, 240323), verbose_name='Data da inscrição:'),
        ),
        migrations.AlterField(
            model_name='trabalhofinal',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador_trabalho_final', to='professor.professor'),
        ),
        migrations.AlterField(
            model_name='versaofinal',
            name='dt_versao',
            field=models.DateField(auto_now=True),
        ),
    ]
