# Generated by Django 3.2.16 on 2023-02-16 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0020_auto_20230216_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhofinal',
            name='dt_cadastro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 11, 53, 41, 689568), verbose_name='Data da inscrição:'),
        ),
    ]
