# Generated by Django 3.2.16 on 2023-02-27 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0021_auto_20230216_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'matricula'},
        ),
        migrations.AlterModelOptions(
            name='trabalhofinal',
            options={'verbose_name_plural': 'Trabalhos Finais'},
        ),
        migrations.AlterModelOptions(
            name='versaofinal',
            options={'verbose_name_plural': 'Versões Finais'},
        ),
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 2, 27, 10, 28, 59, 830246), verbose_name='Data da inscrição:'),
        ),
    ]
