# Generated by Django 3.2.16 on 2023-02-27 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0022_auto_20230227_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(default=datetime.datetime(2023, 2, 27, 11, 41, 22, 717215), verbose_name='Data da inscrição:'),
        ),
    ]
