# Generated by Django 3.2.16 on 2023-03-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0032_alter_probatorio_data_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probatorio',
            name='data_inscricao',
            field=models.DateField(verbose_name='Data da inscrição:'),
        ),
    ]
