# Generated by Django 3.2.16 on 2023-03-01 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0033_alter_probatorio_data_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhofinal',
            name='versao_final',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versao_final_trabalho_final', to='matricula.versaofinal'),
        ),
    ]
