# Generated by Django 3.2.16 on 2023-03-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_linhapesquisa'),
        ('matricula', '0034_alter_trabalhofinal_versao_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='linha_pesquisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.linhapesquisa'),
        ),
        migrations.AddField(
            model_name='probatorio',
            name='linha_pesquisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.linhapesquisa'),
        ),
    ]
