# Generated by Django 3.2.16 on 2023-03-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_grau'),
        ('matricula', '0035_auto_20230313_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='probatorio',
            name='grau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='probatorio_grau', to='config.grau', verbose_name='Grau de Aplicação:'),
            preserve_default=False,
        ),
    ]
