# Generated by Django 3.2.16 on 2023-03-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0037_matricula_grau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalhofinal',
            name='data',
        ),
    ]
