# Generated by Django 3.2.16 on 2023-04-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0005_alter_professor_sexo'),
        ('matricula', '0038_remove_trabalhofinal_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalhofinal',
            name='orientador',
        ),
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Orientador', 'Orientador'), ('Coorientador', 'Coorientador')], max_length=200)),
                ('professor_externo', models.BooleanField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orientacao_professor', to='professor.professor')),
                ('trabalho_final', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orientacao_trabalho_final', to='matricula.trabalhofinal')),
            ],
            options={
                'verbose_name_plural': 'Orientações',
            },
        ),
    ]
