# Generated by Django 3.2.16 on 2023-05-25 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_linguas'),
        ('matricula', '0040_matricula_dt_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameLinguas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('dt_nota', models.DateField(auto_now=True)),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exame_linguas', to='config.linguas')),
                ('probatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probatorio_exame_linguas', to='matricula.probatorio')),
            ],
            options={
                'verbose_name': 'Exame de Lingua',
                'verbose_name_plural': 'Exames de Linguas',
            },
        ),
    ]
