# Generated by Django 3.2.16 on 2023-05-25 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_linguas'),
        ('matricula', '0041_examelinguas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examelinguas',
            name='lingua',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exame_linguas', to='config.linguas'),
        ),
        migrations.AlterField(
            model_name='examelinguas',
            name='probatorio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='probatorio_exame_linguas', to='matricula.probatorio'),
        ),
    ]
