# Generated by Django 3.2.16 on 2023-05-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0042_auto_20230525_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probatorio',
            name='nota',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='probatorio_nota', to='matricula.nota', verbose_name='Nota:'),
        ),
    ]
