# Generated by Django 3.2.16 on 2023-06-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0020_alter_graduacao_instituicao'),
        ('matricula', '0044_alter_examelinguas_lingua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probatorio',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='probatorio_aluno', to='aluno.aluno', verbose_name='Aluno:'),
        ),
    ]
