# Generated by Django 3.2.16 on 2024-01-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0047_auto_20240122_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricaoprobatorio',
            old_name='situação',
            new_name='situacao',
        ),
    ]
