# Generated by Django 3.2.16 on 2024-01-23 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0048_rename_situação_inscricaoprobatorio_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='situacao',
            field=models.CharField(choices=[('Cursando', 'Cursando'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Trancado', 'Trancado')], default=('Cursando', 'Cursando'), max_length=200),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nota',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
