# Generated by Django 3.2.16 on 2024-05-15 14:19

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaFomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=200)),
                ('cor', colorful.fields.RGBColorField(default='#000000')),
            ],
        ),
    ]
