# Generated by Django 3.2.16 on 2024-05-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_agenciafomento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenciafomento',
            old_name='agencia',
            new_name='agencia_fomento',
        ),
    ]
