# Generated by Django 3.2.16 on 2023-02-27 13:29

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_vinculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sexo',
            name='cor',
            field=colorful.fields.RGBColorField(default='black'),
        ),
    ]
