# Generated by Django 3.2.16 on 2023-02-27 15:20

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_estadocivil_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='etnia',
            name='cor',
            field=colorful.fields.RGBColorField(default='black'),
        ),
    ]
