# Generated by Django 3.2.16 on 2023-03-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_etnia_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_options', models.CharField(max_length=50)),
            ],
        ),
    ]
