# Generated by Django 3.2.16 on 2023-03-01 11:44

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_statusoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocivil',
            name='cor',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
        migrations.AlterField(
            model_name='etnia',
            name='cor',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='cor',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
    ]
