# Generated by Django 3.2.16 on 2023-03-13 14:32

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_auto_20230301_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha_pesquisa', models.CharField(max_length=50)),
                ('cor', colorful.fields.RGBColorField(default='#000000')),
            ],
        ),
    ]
