# Generated by Django 3.2.16 on 2023-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_linhapesquisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhapesquisa',
            name='linha_pesquisa',
            field=models.CharField(max_length=200),
        ),
    ]
