# Generated by Django 3.2.16 on 2023-03-23 11:51

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegio', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=200)),
                ('cor', colorful.fields.RGBColorField(default='#000000')),
            ],
        ),
    ]
