# Generated by Django 3.2.16 on 2023-04-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_tipodedocente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipodeDocente',
        ),
    ]
