# Generated by Django 3.2.16 on 2023-04-11 19:47

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_delete_tipodedocente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipodedocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodedocente', models.CharField(max_length=200)),
                ('cor', colorful.fields.RGBColorField(default='#000000')),
            ],
        ),
    ]
