# Generated by Django 3.2.16 on 2023-04-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_tipodedocente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodedocente',
            old_name='tipodedocente',
            new_name='tip_dedocente',
        ),
    ]
