# Generated by Django 3.2.15 on 2022-10-17 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('municipio', models.CharField(blank=True, max_length=200, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao_residencia', models.CharField(blank=True, max_length=200, null=True)),
                ('residencia_ano_inicio', models.IntegerField(blank=True, null=True)),
                ('residencia_ano_fim', models.IntegerField(blank=True, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=200, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titulacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulacao', models.CharField(blank=True, max_length=200, null=True)),
                ('titulacao_area', models.CharField(blank=True, max_length=200, null=True)),
                ('titulacao_ano', models.IntegerField(blank=True, null=True)),
                ('data_qualificacao', models.DateField(blank=True, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('instituicao_titulacao', models.CharField(blank=True, max_length=200, null=True)),
                ('obs_geral', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalho', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_vinculo', models.CharField(blank=True, choices=[('Estatutário', 'Estatutário'), ('CLT', 'CLT'), ('Autônomo', 'Autônomo'), ('Outros', 'Outros')], max_length=200, null=True, verbose_name='Tipo de Vínculo:')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacao_area', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('graduacao_ano_inicio', models.IntegerField(blank=True, null=True)),
                ('graduacao_ano_fim', models.IntegerField(blank=True, null=True)),
                ('residencia', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.residencia')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=2, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_nascimento', models.DateField()),
                ('estado_civil', models.CharField(blank=True, max_length=100, null=True)),
                ('identidade', models.CharField(max_length=12)),
                ('identidade_uf', models.CharField(max_length=2)),
                ('identidade_orgao', models.CharField(max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('etnia', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='dt_cadastro')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dt_cadastro', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.endereco')),
                ('graduacao', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.graduacao')),
                ('titulacao', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.titulacao')),
                ('trabalho', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.trabalho')),
            ],
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afastamento', models.CharField(max_length=200)),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField()),
                ('aluno', models.ManyToManyField(related_name='afastamento_aluno', to='aluno.Aluno')),
            ],
        ),
    ]
