# Generated by Django 3.2.16 on 2024-05-06 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP:')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço:')),
                ('numero', models.CharField(blank=True, max_length=200, null=True, verbose_name='Número:')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento:')),
                ('bairro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro:')),
                ('municipio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Município:')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF:')),
                ('pais', models.CharField(blank=True, max_length=200, null=True, verbose_name='País:')),
                ('telefone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone:')),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 2:')),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao_residencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição:')),
                ('residencia_ano_inicio', models.IntegerField(blank=True, null=True, verbose_name='Ano de Início:')),
                ('residencia_ano_fim', models.IntegerField(blank=True, null=True, verbose_name='Ano de Término:')),
                ('especialidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidade:')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF:')),
            ],
        ),
        migrations.CreateModel(
            name='Titulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulação:')),
                ('titulacao_area', models.CharField(blank=True, max_length=200, null=True, verbose_name='Área:')),
                ('titulacao_ano', models.IntegerField(blank=True, null=True, verbose_name='Ano:')),
                ('data_qualificacao', models.DateField(blank=True, null=True, verbose_name='Data da Qualificação:')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF:')),
                ('instituicao_titulacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição:')),
                ('obs_geral', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalho', models.CharField(blank=True, max_length=200, null=True, verbose_name='Trabalho:')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de trabalho:')),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.endereco')),
                ('tipo_vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.vinculo', verbose_name='Tipo de Vínculo:')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.statusoptions')),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacao_area', models.CharField(max_length=200, verbose_name='Área:')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local:')),
                ('graduacao_ano_inicio', models.IntegerField(blank=True, null=True, verbose_name='Ano de início:')),
                ('graduacao_ano_fim', models.IntegerField(blank=True, null=True, verbose_name='Ano de término:')),
                ('bolsa_graduacao', models.BooleanField(default=False)),
                ('agencia', models.CharField(blank=True, max_length=200, null=True)),
                ('iniciacao_cientifica', models.BooleanField(default=False)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_graduacao_instituicao', to='config.instituicao', verbose_name='Instituição')),
                ('residencia', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.residencia')),
            ],
        ),
        migrations.CreateModel(
            name='EnsinoMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensino_medio_ano_inicio', models.IntegerField(blank=True, null=True, verbose_name='Ano de Início:')),
                ('ensino_medio_ano_conclusao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão:')),
                ('ensino_medio_municipio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Município:')),
                ('ensino_medio_tipo', models.CharField(blank=True, choices=[('Pública', 'Pública'), ('Particular', 'Particular')], max_length=200, null=True, verbose_name='Tipo de instituição:')),
                ('ensino_medio_bolsa', models.BooleanField(default=False, verbose_name='Teve bolsa')),
                ('ensino_medio_bolsa_int_parc', models.CharField(blank=True, choices=[('Integral', 'Integral'), ('Parcial', 'Parcial')], max_length=200, null=True, verbose_name='Tipo de bolsa:')),
                ('ensino_medio_instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.colegio', verbose_name='Colégio:')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome:')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF:')),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do pai:')),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da mãe:')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade:')),
                ('dt_nascimento', models.DateField()),
                ('identidade', models.CharField(max_length=12, verbose_name='Identidade:')),
                ('identidade_uf', models.CharField(max_length=2, verbose_name='UF:')),
                ('identidade_orgao', models.CharField(max_length=100, verbose_name='Orgão expedidor:')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:')),
                ('portador_deficiencia', models.BooleanField()),
                ('portador_deficiencia_qual', models.CharField(blank=True, max_length=200, null=True, verbose_name='Qual deficiência:*')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img')),
                ('slug', models.SlugField(max_length=250, unique_for_date='dt_cadastro')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dt_cadastro', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_endereco', to='aluno.endereco')),
                ('ensino_medio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_ensino_medio', to='aluno.ensinomedio')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.estadocivil', verbose_name='Estado civil:')),
                ('etnia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.etnia', verbose_name='Raça/Etnia:')),
                ('graduacao', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_graduacao', to='aluno.graduacao')),
                ('naturalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.unidadefederativa', verbose_name='Naturalidade:')),
                ('residencia', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_residencia', to='aluno.residencia')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.sexo', verbose_name='Sexo:')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_status', to='aluno.status')),
                ('titulacao', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_titulacao', to='aluno.titulacao')),
                ('trabalho', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_trabalho', to='aluno.trabalho')),
            ],
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afastamento', models.CharField(max_length=200)),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField()),
                ('aluno', models.ManyToManyField(related_name='afastamento_aluno', to='aluno.Aluno')),
            ],
        ),
    ]
