# Generated by Django 2.1.5 on 2022-08-02 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('nome_pai', models.CharField(max_length=200)),
                ('nome_mae', models.CharField(max_length=200)),
                ('naturalidade', models.CharField(max_length=2)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('dt_nascimento', models.DateField()),
                ('estado_civil', models.CharField(max_length=100)),
                ('identidade', models.CharField(max_length=12)),
                ('identidade_uf', models.CharField(max_length=2)),
                ('identidade_orgao', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(max_length=250, unique_for_date='dt_cadastro')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_cadastrado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacao_area', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('graduacao_ano_inicio', models.IntegerField()),
                ('graduacao_ano_fim', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao_residencia', models.CharField(max_length=200)),
                ('residencia_ano_inicio', models.IntegerField()),
                ('residencia_ano_fim', models.IntegerField()),
                ('especialidade', models.CharField(max_length=200)),
                ('orientador', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Titulacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulacao', models.CharField(max_length=200)),
                ('titulacao_area', models.CharField(max_length=200)),
                ('titulacao_ano', models.IntegerField()),
                ('uf', models.CharField(max_length=2)),
                ('instituicao', models.CharField(max_length=200)),
                ('obs_geral', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalho', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('data_termino', models.DateField()),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.Endereco')),
            ],
        ),
        migrations.AddField(
            model_name='graduacao',
            name='residencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.Residencia'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.Endereco'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='graduacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.Graduacao'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='titulacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.Titulacao'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='trabalho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.Trabalho'),
        ),
    ]
