# Generated by Django 2.1.5 on 2022-08-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulacao',
            old_name='titulacaoarea',
            new_name='titulacao_area',
        ),
    ]
