# Generated by Django 3.2.16 on 2025-04-02 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_rename_agencia_agenciafomento_agencia_fomento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cadastrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.estadocivil', verbose_name='Estado civil:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='etnia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.etnia', verbose_name='Raça/Etnia:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.unidadefederativa', verbose_name='Naturalidade:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.sexo', verbose_name='Sexo:'),
        ),
    ]
