# Generated by Django 3.2.16 on 2022-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do pai:'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='trabalho',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Trabalho:'),
        ),
    ]
