# Generated by Django 3.2.15 on 2022-10-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='raca',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='orientador',
        ),
        migrations.AddField(
            model_name='trabalho',
            name='tipo_vinculo',
            field=models.CharField(blank=True, choices=[('Estatutário', 'Estatutário'), ('CLT', 'CLT'), ('Autônomo', 'Autônomo'), ('Outros', 'Outros')], max_length=200, null=True, verbose_name='Tipo de Vínculo:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='telefone1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='graduacao_ano_fim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='graduacao_ano_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='especialidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='instituicao_residencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='residencia_ano_fim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='residencia_ano_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='data_qualificacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='instituicao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='obs_geral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='titulacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='titulacao_ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='titulacao_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.endereco'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='trabalho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
