# Generated by Django 3.2.16 on 2023-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro:'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento:'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Número:'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='País:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado civil:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='etnia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etnia:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='identidade',
            field=models.CharField(max_length=12, verbose_name='Identidade:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='identidade_orgao',
            field=models.CharField(max_length=100, verbose_name='Orgão expedidor:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='identidade_uf',
            field=models.CharField(max_length=2, verbose_name='UF:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Naturalidade:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da mãe:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=50, null=True, verbose_name='Sexo:'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação:'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP:'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Município:'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='telefone1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 2:'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF:'),
        ),
        migrations.AlterField(
            model_name='ensinomedio',
            name='ensino_medio_ano_conclusao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão:'),
        ),
        migrations.AlterField(
            model_name='ensinomedio',
            name='ensino_medio_ano_inicio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Início:'),
        ),
        migrations.AlterField(
            model_name='ensinomedio',
            name='ensino_medio_instituicao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição:'),
        ),
        migrations.AlterField(
            model_name='ensinomedio',
            name='ensino_medio_municipio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Município:'),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='graduacao_ano_fim',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de término:'),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='graduacao_ano_inicio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de início:'),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='graduacao_area',
            field=models.CharField(max_length=200, verbose_name='Área:'),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='instituicao',
            field=models.CharField(max_length=200, verbose_name='Instituição:'),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local:'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='especialidade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidade:'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='instituicao_residencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição:'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='residencia_ano_fim',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Término:'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='residencia_ano_inicio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Início:'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF:'),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='data_qualificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Qualificação:'),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='instituicao_titulacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição:'),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='obs_geral',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='titulacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulação:'),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='titulacao_ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano:'),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='titulacao_area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Área:'),
        ),
        migrations.AlterField(
            model_name='titulacao',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF:'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de trabalho:'),
        ),
    ]
