# Generated by Django 2.1.5 on 2022-07-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='uf',
            new_name='naturalidade',
        ),
    ]
