# Generated by Django 3.2.16 on 2022-10-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20221010_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='situacao',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
