# Generated by Django 3.2.16 on 2023-01-31 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('aluno', '0002_auto_20230130_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.unidadefederativa', verbose_name='Naturalidade:'),
        ),
    ]
