# Generated by Django 3.2.16 on 2022-10-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_aluno_situacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulacao',
            old_name='instituicao',
            new_name='instituicao_titulacao',
        ),
    ]
