# Generated by Django 3.2.16 on 2022-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduacao',
            name='agencia',
            field=models.CharField(default=None, max_length=200, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduacao',
            name='bolsa_graduacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graduacao',
            name='iniciacao_cientifica',
            field=models.BooleanField(default=False),
        ),
    ]
