# Generated by Django 3.2.16 on 2022-11-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_auto_20221101_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacao',
            name='agencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
