# Generated by Django 3.2.16 on 2022-10-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_rename_instituicao_titulacao_instituicao_titulacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
