# Generated by Django 3.2.16 on 2022-11-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_alter_graduacao_agencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_endereco', to='aluno.endereco'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='graduacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_graduacao', to='aluno.graduacao'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='titulacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_titulacao', to='aluno.titulacao'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='trabalho',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_trabalho', to='aluno.trabalho'),
        ),
    ]
