# Generated by Django 3.2.16 on 2023-01-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_auto_20230105_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensinomedio',
            name='ensino_medio_tipo',
            field=models.CharField(blank=True, choices=[('Pública', 'Pública'), ('Particular', 'Particular')], max_length=200, null=True, verbose_name='Tipo de instituição:'),
        ),
    ]
