# Generated by Django 3.2.16 on 2023-03-01 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_auto_20230301_0912'),
        ('aluno', '0010_auto_20230301_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_endereco', to='aluno.endereco'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ensino_medio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_ensino_medio', to='aluno.ensinomedio'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='graduacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_graduacao', to='aluno.graduacao'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='residencia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_residencia', to='aluno.residencia'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_status', to='aluno.status'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='titulacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_titulacao', to='aluno.titulacao'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='trabalho',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_trabalho', to='aluno.trabalho'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.statusoptions'),
        ),
    ]
