# Generated by Django 3.2.16 on 2023-03-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_colegio'),
        ('aluno', '0012_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensinomedio',
            name='ensino_medio_instituicao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Colégio:'),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.instituicao', verbose_name='Instituição:'),
        ),
    ]
