# Generated by Django 3.2.16 on 2023-03-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_colegio'),
        ('aluno', '0013_auto_20230323_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensinomedio',
            name='ensino_medio_instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.colegio', verbose_name='Colégio:'),
        ),
    ]
