# Generated by Django 3.2.16 on 2023-03-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_grau'),
        ('aluno', '0014_alter_ensinomedio_ensino_medio_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='portador_deficiencia',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='portador_deficiencia_qual',
            field=models.CharField(default=1, max_length=200, verbose_name='Qual deficiência:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.instituicao', verbose_name='Instituição'),
        ),
    ]
