# Generated by Django 3.2.16 on 2023-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0016_alter_aluno_portador_deficiencia_qual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='portador_deficiencia_qual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qual deficiência:*'),
        ),
    ]
