# Generated by Django 3.2.16 on 2023-04-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0017_alter_aluno_portador_deficiencia_qual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='situacao',
        ),
    ]
