# Generated by Django 3.2.16 on 2023-04-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_grau'),
        ('aluno', '0019_alter_aluno_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno_graduacao_instituicao', to='config.instituicao', verbose_name='Instituição'),
        ),
    ]
