# Generated by Django 3.2.16 on 2024-01-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0020_alter_graduacao_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensinomedio',
            name='ensino_medio_bolsa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ensinomedio',
            name='ensino_medio_bolsa_int_parc',
            field=models.CharField(blank=True, choices=[('Integral', 'Integral'), ('Parcial', 'Parcial')], max_length=200, null=True),
        ),
    ]
