# Generated by Django 3.2.16 on 2024-01-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0021_auto_20240122_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensinomedio',
            name='ensino_medio_bolsa',
            field=models.BooleanField(default=False, verbose_name='Teve bolsa'),
        ),
        migrations.AlterField(
            model_name='ensinomedio',
            name='ensino_medio_bolsa_int_parc',
            field=models.CharField(blank=True, choices=[('Integral', 'Integral'), ('Parcial', 'Parcial')], max_length=200, null=True, verbose_name='Tipo de bolsa:'),
        ),
    ]
