# Generated by Django 2.1.5 on 2022-07-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=50)),
                ('dt_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=100)),
                ('naturalidade', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=14)),
                ('identidade', models.CharField(max_length=12)),
                ('identidade_uf', models.CharField(max_length=100)),
                ('identidade_orgao', models.CharField(max_length=100)),
                ('CRM', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=2)),
                ('Siape', models.CharField(max_length=30)),
            ],
        ),
    ]
