# Generated by Django 3.2.16 on 2024-05-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegiado_membro', models.BooleanField(default=False)),
                ('colegiado_data_entrada', models.DateField(blank=True, null=True)),
                ('colegiado_data_saida', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacao_area', models.CharField(max_length=200, verbose_name='Área:')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local:')),
                ('graduacao_ano_inicio', models.IntegerField(blank=True, null=True, verbose_name='Ano de início:')),
                ('graduacao_ano_fim', models.IntegerField(blank=True, null=True, verbose_name='Ano de término:')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_graduacao_instituicao', to='config.instituicao', verbose_name='Instituição')),
            ],
        ),
        migrations.CreateModel(
            name='PosDoutorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(verbose_name='Concluído:')),
                ('ano_inicio', models.IntegerField(blank=True, null=True, verbose_name='Ano de início:')),
                ('ano_fim', models.IntegerField(blank=True, null=True, verbose_name='Ano de término:')),
                ('pais', models.CharField(blank=True, max_length=200, null=True, verbose_name='País:')),
                ('instituicao_posdoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.instituicao', verbose_name='Instituição de Pós-doutorado:')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Setor:')),
                ('admissao', models.DateField(blank=True, null=True, verbose_name='Admissão:')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo:')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone:')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True, verbose_name='Categoria:')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:')),
                ('instituicao_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.instituicao', verbose_name='Instituição:')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome:')),
                ('dt_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento:')),
                ('estrangeiro', models.BooleanField(default=False, verbose_name='Estrangeiro:')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade:')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF:')),
                ('identidade', models.CharField(blank=True, max_length=12, null=True, verbose_name='Identidade:')),
                ('identidade_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF:')),
                ('identidade_orgao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Orgão Expeditor:')),
                ('tipo_docente', models.CharField(blank=True, choices=[('Permanente', 'Permanente'), ('Colaborador', 'Colaborador'), ('Coorientador', 'Coorientador'), ('Visitante', 'Visitante'), ('Pos Doutor', 'Pós Doutor')], max_length=100, null=True, verbose_name='Tipo de docente:')),
                ('slug', models.SlugField(max_length=250, unique_for_date='dt_cadastro')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.endereco')),
                ('graduacao', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_graduacao', to='professor.graduacao')),
                ('membro_colegiado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_membro_colegiado', to='professor.colegiado')),
                ('naturalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.unidadefederativa', verbose_name='Naturalidade:')),
                ('pos_doutorado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_pos_doutorado', to='professor.posdoutorado')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.sexo', verbose_name='Sexo:')),
                ('titulacao', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.titulacao')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_trabalho', to='professor.trabalho')),
            ],
        ),
    ]
