# Generated by Django 3.2.16 on 2024-05-06 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doutorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doutorado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doutorado:')),
                ('doutorado_area', models.CharField(blank=True, max_length=200, null=True, verbose_name='Área:')),
                ('doutorado_ano', models.IntegerField(blank=True, null=True, verbose_name='Ano:')),
                ('data_qualificacao', models.DateField(blank=True, null=True, verbose_name='Data da Qualificação:')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF:')),
                ('instituicao_doutorado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição:')),
                ('obs_geral', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='titulacao',
        ),
        migrations.AddField(
            model_name='professor',
            name='doutorado',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='professor.doutorado'),
            preserve_default=False,
        ),
    ]
