# Generated by Django 2.1.5 on 2022-08-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='pos_doutorado',
            new_name='Pos_Doutorado',
        ),
    ]
