# Generated by Django 2.1.5 on 2022-07-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='identidade_uf',
            field=models.CharField(max_length=2),
        ),
    ]
