# Generated by Django 3.2.16 on 2022-10-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_alter_posdoutorado_concluido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posdoutorado',
            old_name='instituicao',
            new_name='instituicao_posdoc',
        ),
        migrations.RenameField(
            model_name='trabalho',
            old_name='instituicao',
            new_name='instituicao_trabalho',
        ),
    ]
