# Generated by Django 2.1.5 on 2022-08-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_auto_20220812_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='Pos_Doutorado',
            new_name='pos_doutorado',
        ),
    ]
