# Generated by Django 3.2.16 on 2024-05-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20240506_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posdoutorado',
            name='ano_inicio',
        ),
        migrations.RemoveField(
            model_name='posdoutorado',
            name='concluido',
        ),
        migrations.AddField(
            model_name='posdoutorado',
            name='pos_doutorado',
            field=models.BooleanField(default=1, verbose_name='Tem Pós-Doutorado?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doutorado',
            name='doutorado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Doutorado:'),
        ),
    ]
