# Generated by Django 3.2.16 on 2023-03-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_instituicaoresidencia'),
        ('professor', '0003_auto_20230207_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdoutorado',
            name='instituicao_posdoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.instituicao', verbose_name='Instituição de Pós-doutorado:'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.unidadefederativa', verbose_name='Naturalidade:'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='instituicao_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.instituicao', verbose_name='Instituição:'),
        ),
    ]
