# Generated by Django 3.2.16 on 2024-05-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_auto_20240506_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegiado',
            name='colegiado_membro',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='membro_colegiado',
        ),
        migrations.AddField(
            model_name='professor',
            name='membro_colegiado',
            field=models.ManyToManyField(blank=True, null=True, to='professor.Colegiado'),
        ),
    ]
