# Generated by Django 3.2.16 on 2024-05-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0005_auto_20240520_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegiado',
            name='status_membro',
            field=models.CharField(choices=[('Titular', 'Titular'), ('Suplente', 'Suplente')], default='Titular', max_length=100, verbose_name='Status:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colegiado',
            name='colegiado_data_entrada',
            field=models.DateField(default='2020-05-05'),
            preserve_default=False,
        ),
    ]
