# Generated by Django 3.2.16 on 2023-04-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_grau'),
        ('professor', '0005_alter_professor_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacao_area', models.CharField(max_length=200, verbose_name='Área:')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local:')),
                ('graduacao_ano_inicio', models.IntegerField(blank=True, null=True, verbose_name='Ano de início:')),
                ('graduacao_ano_fim', models.IntegerField(blank=True, null=True, verbose_name='Ano de término:')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_graduacao_instituicao', to='config.instituicao', verbose_name='Instituição')),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='graduacao',
            field=models.OneToOneField(default=14, on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_graduacao', to='professor.graduacao'),
            preserve_default=False,
        ),
    ]
