# Generated by Django 3.2.16 on 2024-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0006_auto_20240520_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='membro_colegiado',
            field=models.ManyToManyField(blank=True, related_name='professor_colegiado', to='professor.Colegiado'),
        ),
    ]
