# Generated by Django 3.2.16 on 2024-09-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0007_alter_professor_membro_colegiado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='membro_colegiado',
        ),
        migrations.AddField(
            model_name='professor',
            name='membro_colegiado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professor.colegiado'),
        ),
    ]
