# Generated by Django 3.2.16 on 2024-09-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0013_remove_matricula_membro_colegiado'),
        ('professor', '0008_auto_20240922_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='membro_colegiado',
        ),
        migrations.DeleteModel(
            name='Colegiado',
        ),
    ]
