# Generated by Django 3.2.16 on 2024-05-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=200, verbose_name='Nome do evento:')),
                ('evento_data', models.DateField(verbose_name='Data do evento:')),
                ('evento_hora', models.TimeField(verbose_name='Hora:')),
                ('slug', models.SlugField(max_length=250, unique_for_date='dt_cadastro')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dt_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante_tipo', models.CharField(choices=[('Orientador', 'Orientador'), ('Coorientador', 'Coorientador'), ('Banca', 'Banca')], max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_evento', to='evento.evento')),
            ],
        ),
    ]
