# Generated by Django 3.2.16 on 2023-01-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matricula', '0004_alter_probatorio_data_inscricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante_nome', models.CharField(max_length=200)),
                ('participante_tipo', models.CharField(choices=[('Orientador', 'Orientador'), ('Coorientador', 'Coorientador'), ('Banca', 'Banca')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=200)),
                ('evento_data_hora', models.DateTimeField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='dt_cadastro')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dt_cadastro', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evento_cadastrado_por', to=settings.AUTH_USER_MODEL)),
                ('evento_participantes', models.ManyToManyField(related_name='evento_participantes', to='evento.Participante')),
                ('evento_trabalho_final', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evento_trabalho_final', to='matricula.trabalhofinal')),
            ],
        ),
    ]
