# Generated by Django 3.2.16 on 2024-05-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('matricula', '0001_initial'),
        ('evento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='participante_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_professor', to='professor.professor'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cadastrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evento_cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_trabalho_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_trabalho_final', to='matricula.trabalhofinal', verbose_name='Trabalho final:'),
        ),
    ]
