# Generated by Django 3.2.16 on 2023-01-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_alter_probatorio_data_inscricao'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='evento',
            field=models.CharField(max_length=200, verbose_name='Nome do evento:'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='evento_data',
            field=models.DateField(verbose_name='Data do evento:'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='evento_hora',
            field=models.TimeField(verbose_name='Hora:'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='evento_trabalho_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_trabalho_final', to='matricula.trabalhofinal', verbose_name='Trabalho final:'),
        ),
    ]
