# Generated by Django 3.2.16 on 2023-01-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='evento_data_hora',
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_data',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_hora',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
