# Generated by Django 3.2.16 on 2023-01-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
        ('evento', '0002_auto_20230110_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='evento_participantes',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='participante_nome',
        ),
        migrations.AddField(
            model_name='participante',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participantes_evento', to='evento.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participante',
            name='participante_professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participante_professor', to='professor.professor'),
            preserve_default=False,
        ),
    ]
