# Generated by Django 3.2.16 on 2024-07-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0010_auto_20240711_1447'),
        ('evento', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='Tipo: ',
            field=models.CharField(choices=[('Qualificação', 'Qualificação'), ('Defesa de Dissertação', 'Defesa de Dissertação'), ('Defesa de Tese', 'Defesa de Tese'), ('Seminários', 'Seminários'), ('Palestras', 'Palestras'), ('Encontros', 'Encontros')], default='Defesa de Dissertação', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='evento_trabalho_final',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_trabalho_final', to='matricula.trabalhofinal', verbose_name='Trabalho final:'),
        ),
    ]
