# Generated by Django 3.2.16 on 2023-01-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_auto_20230110_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_evento', to='evento.evento'),
        ),
    ]
