# Generated by Django 3.2.16 on 2024-07-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0010_auto_20240711_1447'),
        ('evento', '0003_auto_20240711_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='evento_trabalho_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_trabalho_final', to='matricula.trabalhofinal', verbose_name='Trabalho final:'),
        ),
    ]
