# Generated by Django 3.2.16 on 2023-01-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0008_alter_probatorio_data_inscricao'),
        ('evento', '0004_alter_participante_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='evento_trabalho_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_trabalho_final', to='matricula.trabalhofinal'),
        ),
    ]
