# Generated by Django 3.2.16 on 2024-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_alter_evento_evento_trabalho_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='Tipo: ',
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_tipo',
            field=models.CharField(choices=[('Qualificação', 'Qualificação'), ('Defesa de Dissertação', 'Defesa de Dissertação'), ('Defesa de Tese', 'Defesa de Tese'), ('Seminários', 'Seminários'), ('Palestras', 'Palestras'), ('Encontros', 'Encontros')], default='Tese de Dissertação', max_length=200, verbose_name='Tipo: '),
            preserve_default=False,
        ),
    ]
