# Generated by Django 3.2.16 on 2024-07-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_auto_20240712_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidados',
            name='convidado',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convidados',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='convidados_evento', to='evento.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palestrante',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='palestrante_evento', to='evento.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palestrante',
            name='palestrante',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
