# Generated by Django 3.2.16 on 2024-07-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_auto_20240712_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidados',
            name='convidado_tipo',
            field=models.CharField(choices=[('Palestrante', 'Palestrante'), ('Organizador', 'Organizador')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Palestrante',
        ),
    ]
