# Generated by Django 3.2.16 on 2024-07-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_auto_20240712_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
